permalink   : /:categories/:year/:title/
markdown    : kramdown

paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: Test
description: "The description"
email: info@richardramos.me
baseurl: "" 
# url: ""
repository: "https://github.com/richard-ramos/richard-ramos.github.io"

footer: yes
footer_url: "https://someurl.com"
footer_text: "Page design by Ankit Sultana"

nav:
 - name: "About"
   link: "/test/"
 - name: "Contact"
   link: "contact"
