title: Hello, I'm RichÎ›rd
author: Richard # Your name 
email: info@richardramos.me # your email shown in the footer
url: https://richard-ramos.github.io # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  This is my website where I write about programming, technology, electronics, science, fitness, books I've read and other random stuff.
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://avatars1.githubusercontent.com/u/1106587?s=460&u=b172ba00750423aa164e8426b52c3b17c359b23c&v=4" # avatar in about page
  about_you: a short description about you. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    twitter: richardramos_me
    github:  richard-ramos
    rss: RSS
    # dribbble: 
    # facebook: huangyz0918
    # flickr:   
    # instagram: 
    # linkedin: yizheng-huang
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
remote_theme: richard-ramos/richard-ramos.github.io # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
